---

# Handle *.consul DNS names locally via consul embedded DNS service
# forward the rest of the names to proper DNS server
- name: Install dnsmasq
  apt: name=dnsmasq

- name: And disable dnsmasq right away
  service: name=dnsmasq state=stopped enabled=false

- name: configure dnsmasq
  copy: >
    content='server=/{{ consul_domain }}/127.0.0.1#8600'
    dest=/etc/dnsmasq.d/10-consul
  notify:
    - restart dnsmasq
