---

# This one is run against base AMI image with Packer for example 
- name: Add consul deb repository
  hosts: ec2hosts
  sudo: true

  tasks:

  - name: Add consul deb repo
    apt_repository: repo='ppa:bcandrea/consul'

  - name: Install consul package
    apt: name=consul

  - name: Install consul user interface
    apt: name=consul-web-ui

  - name: Make sure consul agent is not running
    service: name=consul state=stopped enabled=false

  - name: Install dnsmasq
  # Handle *.consul DNS names locally via consul embedded DNS service
  # forward the rest of the names to proper DNS server
    apt: name=dnsmasq
