---

# This one is run against base AMI image with Packer for example 
- name: Add consul deb repository
  hosts: ec2hosts
  sudo: true

  tasks:

  - name: Add consul deb repo
    apt_repository: repo='ppa:bcandrea/consul'

  - name: Install consul package
    apt: name=consul

  - name: Install consul user interface
    apt: name=consul-web-ui

  - name: Make sure consul agent is not running
    service: name=consul state=stopped enabled=false

  - include: ../tasks/dnsmasq.yml
    vars:
      consul_domain: consul.

  handlers:
    - include: ../handlers/dnsmasq.yml