---
# Meta playbook with multiple hosts defined, as the first playbook uses local+ec2 module
# and builds a dynamic hosts group, than the second one uses this group to run scenarios on it

- include: spin-off-ec2-instances.yml
- include: install-consul.yml
# - include: terminate-ec2-instances.yml
