---
- hosts: pseudo_ec2
  gather_facts: False
  tasks:
    - name: Provision a set of instances
      ec2:
         key_name: biom@exoplanet
         instance_type: t2.micro
         image: "{{ ec2_base_ami_image_id }}"
         wait: true 
         region: "{{ ec2_region }}"
         exact_count: "{{ total_instances_count }}"

         assign_public_ip: yes
         group_id: "{{ ec2_security_group_id }}"
         vpc_subnet_id: "{{ ec2_vpc_subnet_id }}"

         count_tag:
            Name: Consulable
            consulable: "true"
         instance_tags:
            Name: Ansible multi instance rollout
      register: ec2

    - name: Add all instance public IPs to host group
      add_host: hostname={{ item.public_dns_name }} groupname=ec2hosts
      with_items: ec2.instances

    - name: Wait for SSH to come up
      wait_for: host={{ item.public_dns_name }} port=22 delay=10 timeout=320 state=started
      with_items: ec2.instances
